[project]
name = "gameflow-analytics-dashboard"
version = "0.1.0"
description = "GameFlow Analytics Dashboard powered by BigQuery"
authors = [
    {name = "Nima Dadkhah",email = "nima.dadkhah.te@gmail.com"}
]
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "streamlit>=1.56.0,<2.0.0",
    "google-cloud-bigquery>=3.11.0",
    "db-dtypes>=1.1.1",
    "pandas>=2.0.0",
    "altair>=5.0.0",
    "numpy (>=2.4.4,<3.0.0)",
    "plotly (>=6.7.0,<7.0.0)"
]


[build-system]
requires = ["poetry-core>=2.0.0,<3.0.0"]
build-backend = "poetry.core.masonry.api"

[tool.poetry]
package-mode = false
